---
folders:
- name: TeamA
  securityGroups: 
  - TEAM-A-DEVELOPER
  - TEAM-A-ADMINISTRATOR
  projects:
  - name: first-project
    defaultBranch: main
  - name: second-project
- name: TeamB
  securityGroups: 
  - TEAM-B-DEVELOPER
  - TEAM-B-ADMINISTRATOR
  folders:
  - name: configurations
    projects:
    - name: app-a-configuration
      jiraProject: config-management
      expectedIssueStatus: APPROVED
    - name: app-b-configuration